import { useState } from 'react';
import GeneratorApp from '../components/GeneratorApp/GeneratorApp';
import { Link } from '../components/Link/Link';

const pageStyles: React.CSSProperties = {
  minHeight: '100vh',
  fontFamily: 'var(--font-body)',
  color: 'var(--text)',
};

const seoSectionStyles: React.CSSProperties = {
  maxWidth: '1024px',
  margin: '0 auto',
  padding: '4rem 1.5rem',
  borderTop: '1px solid var(--border)',
};

const h2Style: React.CSSProperties = {
  fontFamily: 'var(--font-display)',
  fontSize: '1.75rem',
  fontWeight: 800,
  marginBottom: '1rem',
  letterSpacing: '-0.02em',
  color: 'var(--text)',
};

const h3Style: React.CSSProperties = {
  fontFamily: 'var(--font-display)',
  fontSize: '1.15rem',
  fontWeight: 700,
  marginBottom: '0.5rem',
  color: 'var(--text)',
};

const pStyle: React.CSSProperties = {
  color: 'var(--text-muted)',
  lineHeight: 1.7,
  marginBottom: '1rem',
  fontSize: '1rem',
};

// ── FAQ Data (must mirror the FAQPage schema in index.html exactly) ──────────
const FAQS = [
  {
    q: 'Is the business name generator free to use?',
    a: 'Yes — UniqueBusinessName.com is 100% free. There are no hidden fees, no credit card required, and no limit on the number of spins. Generate as many business name ideas as you need, completely free of charge.',
  },
  {
    q: 'Can I trademark a name I get from this tool?',
    a: 'The names generated by this tool are not pre-cleared for trademark. Before attempting to register a name with the USPTO (or your country\'s equivalent), you must conduct a thorough trademark search. A name that appears brandable may already be in use. We strongly recommend consulting a trademark attorney before filing.',
  },
  {
    q: 'How do I check if a business name is already taken?',
    a: 'Start with a free search on the USPTO TESS database (tmsearch.uspto.gov) for trademark conflicts. Also check your state\'s Secretary of State business name database for entity registrations. Finally, search Google and run a domain availability check — a name with an available .com domain is a strong signal it\'s not heavily used.',
  },
  {
    q: 'How does the business name generator work?',
    a: 'We maintain a curated database of highly brandable names across dozens of industries. When you select a category — such as Tech, Bakery, or Fitness — the tool selects a random subset of names and loads them onto the wheel. Our physics engine then simulates realistic angular momentum, friction, and deceleration to pick a winner in a visually satisfying spin.',
  },
  {
    q: 'Can I use this tool for things other than business names?',
    a: 'Absolutely. Switch to "Daily Choices" mode at /decision-wheel to enter your own custom options for any random decision — from picking a restaurant to choosing a workout. Or visit /spirit-animal for a fun spirit animal reveal. All three modes use the same physics-driven wheel.',
  },
  {
    q: 'What makes a good business name?',
    a: 'The best business names are short (1-3 syllables), easy to spell, easy to pronounce, and meaningful or evocative. They should have an available .com domain, no existing trademark conflicts, and no negative connotations in other languages if you plan to operate internationally. Avoid overly generic names that are hard to protect legally.',
  },
];

function FAQAccordion() {
  const [openIndex, setOpenIndex] = useState<number>(0);
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginTop: '2rem' }}>
      {FAQS.map((faq, i) => {
        const isOpen = openIndex === i;
        return (
          <div
            key={i}
            style={{
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius-md)',
              overflow: 'hidden',
              boxShadow: isOpen ? 'var(--shadow-sm)' : 'none',
              transition: 'all 0.2s ease',
            }}
          >
            <button
              onClick={() => setOpenIndex(isOpen ? -1 : i)}
              style={{
                width: '100%',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                padding: '1.25rem 1.5rem',
                background: 'transparent',
                border: 'none',
                color: 'var(--text)',
                fontFamily: 'var(--font-display)',
                fontSize: '1.05rem',
                fontWeight: 600,
                cursor: 'pointer',
                textAlign: 'left',
              }}
            >
              {faq.q}
              <span style={{
                transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)',
                transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                color: isOpen ? 'var(--primary)' : 'var(--text-dim)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '24px',
                height: '24px',
              }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M19 9l-7 7-7-7" />
                </svg>
              </span>
            </button>
            <div style={{
              maxHeight: isOpen ? '250px' : '0',
              opacity: isOpen ? 1 : 0,
              overflow: 'hidden',
              transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
              background: 'var(--surface-2)',
            }}>
              <p style={{ margin: 0, padding: '0 1.5rem 1.25rem', color: 'var(--text-muted)', lineHeight: 1.6, fontSize: '0.95rem' }}>
                {faq.a}
              </p>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default function Home() {
  return (
    <div style={pageStyles}>

      {/* ── Pre-rendered H1 Hero (visible to crawlers before JS) ─────────── */}
      <section style={{ maxWidth: '1024px', margin: '0 auto', padding: '2.5rem 1.5rem 0' }}>
        <h1 style={{
          fontFamily: 'var(--font-display)',
          fontSize: 'clamp(2rem, 5vw, 3.25rem)',
          fontWeight: 900,
          letterSpacing: '-0.04em',
          lineHeight: 1.1,
          color: 'var(--text)',
          marginBottom: '1.25rem',
        }}>
          Free Business Name Generator —{' '}
          <span style={{ color: 'var(--primary)' }}>Spin the Wheel</span> for Instant Brand Name Ideas
        </h1>
        <p style={{ ...pStyle, fontSize: '1.15rem', maxWidth: '700px' }}>
          Struggling to name your new venture? UniqueBusinessName.com's physics-driven Anti-Gravity Wheel
          generates unique, creative, and brandable business name ideas in seconds — completely free.
          Choose from dozens of industry categories (tech, food, fashion, fitness, and more), spin the wheel,
          and instantly get a curated shortlist of names worth building a brand around. Trusted by startups,
          freelancers, and small business owners who want a name that stands out from day one.
          No sign-up. No limits. Just great names.
        </p>
      </section>

      {/* ── Interactive Wheel ─────────────────────────────────────────────── */}
      <GeneratorApp />

      {/* ── SEO Content: How It Works + Tips + FAQ ───────────────────────── */}
      <section style={seoSectionStyles} aria-label="About this tool">

        {/* How It Works */}
        <div style={{ marginBottom: '4rem' }}>
          <h2 style={h2Style}>How the Business Name Generator Works</h2>
          <p style={pStyle}>
            Getting great business name ideas takes just four steps. The entire process takes under a minute.
          </p>
          <ol style={{ paddingLeft: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem', color: 'var(--text-muted)', lineHeight: 1.7 }}>
            <li>
              <strong style={{ color: 'var(--text)' }}>1. Choose your industry category.</strong>{' '}
              Select from 30+ categories — Restaurant, Tech Startup, Clothing Brand, Law Firm, and many more.
              Each category has a curated pool of highly brandable names specific to that field.
            </li>
            <li>
              <strong style={{ color: 'var(--text)' }}>2. Load the wheel.</strong>{' '}
              Click "Load Names" and the wheel is instantly populated with a random selection of 10 names
              from your chosen category. Every load produces a fresh combination — you'll never see the same set twice.
            </li>
            <li>
              <strong style={{ color: 'var(--text)' }}>3. Spin it.</strong>{' '}
              Hit the big "SPIN THE WHEEL" button (or press Space). The Anti-Gravity physics engine fires up,
              simulating real angular momentum, speed-dependent friction, and weighted deceleration for
              a satisfying, authentic spin every time.
            </li>
            <li>
              <strong style={{ color: 'var(--text)' }}>4. Check your winner.</strong>{' '}
              When the wheel stops, your business name idea is revealed. You can immediately check domain
              availability, spin again for more ideas, or save your favourite to the history panel.
            </li>
          </ol>
        </div>

        {/* Tips Grid */}
        <div style={{ marginBottom: '4rem' }}>
          <h2 style={h2Style}>Tips for Choosing a Great Business Name</h2>
          <p style={pStyle}>
            A great business name is one of your most powerful branding assets. It affects how customers
            find you, remember you, and talk about you. Here are the four most important factors to evaluate
            before committing to a name.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '2rem', marginTop: '2rem' }}>

            <div style={{ padding: '1.5rem', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
              <h3 style={h3Style}>✂️ Keep It Short and Memorable</h3>
              <p style={{ ...pStyle, marginBottom: 0 }}>
                Aim for one to three syllables. Short names are easier to say, easier to spell, and far easier
                to remember. Think of iconic brands — Apple, Nike, Stripe, Lyft. If someone has to ask you to
                spell your business name twice over the phone, it's a red flag. The generator prioritises
                punchy, memorable names over long descriptive phrases.
              </p>
            </div>

            <div style={{ padding: '1.5rem', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
              <h3 style={h3Style}>🌐 Check Domain Availability First</h3>
              <p style={{ ...pStyle, marginBottom: 0 }}>
                Before you fall in love with a name, verify that the .com domain is available. A .com
                isn't strictly required in 2026 — .io, .co, and .ai are widely accepted — but .com still
                carries the most credibility and is the default expectation for most consumers. Run a quick
                search on Namecheap or GoDaddy before registering any business entity under that name.
              </p>
            </div>

            <div style={{ padding: '1.5rem', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
              <h3 style={h3Style}>⚖️ Avoid Trademark Conflicts</h3>
              <p style={{ ...pStyle, marginBottom: 0 }}>
                Using a name that is already trademarked — even unintentionally — can result in a
                cease-and-desist letter, forced rebrand, and legal costs. Always search the USPTO TESS
                database (for the US) and your country's equivalent before filing your business registration.
                Pay attention not just to identical matches, but to confusingly similar names in the same
                industry class.
              </p>
            </div>

            <div style={{ padding: '1.5rem', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
              <h3 style={h3Style}>🗣️ Make It Easy to Say and Spell</h3>
              <p style={{ ...pStyle, marginBottom: 0 }}>
                Word-of-mouth is still the most powerful marketing channel. If your business name is
                difficult to pronounce or has an unexpected spelling, you're working against every
                referral. Test your shortlisted names by saying them out loud to someone unfamiliar
                with the brand. If they hesitate, misspell it on first attempt, or ask for clarification,
                consider that a strong signal to look at alternatives.
              </p>
            </div>
          </div>
        </div>

        {/* FAQ + Features Grid */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '3rem',
          alignItems: 'start',
        }}>
          {/* Features */}
          <div>
            <h2 style={h2Style}>Why Use UniqueBusinessName.com?</h2>
            <p style={pStyle}>
              Unlike static name generators that spit out the same generic suggestions every visit,
              our physics-driven wheel makes each session feel different — and genuinely fun.
            </p>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '0.85rem', color: 'var(--text-muted)' }}>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>100% Free &amp; No Signup:</strong> Generate unlimited ideas without creating an account.</span>
              </li>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>Physics Engine:</strong> Real momentum, friction, and bounce for authentic spins — not just a random number.</span>
              </li>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>Domain Checking:</strong> Found the perfect brand name? Check domain availability instantly from the result panel.</span>
              </li>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>30+ Industry Categories:</strong> From SaaS startups to local bakeries — curated name pools for every niche.</span>
              </li>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>Spin History:</strong> All your results are saved locally so you can review and compare past ideas.</span>
              </li>
              <li style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--success)', fontWeight: 700, flexShrink: 0 }}>✓</span>
                <span><strong>Works Offline:</strong> Installed as a PWA, the generator works even without an internet connection.</span>
              </li>
            </ul>

            {/* Also Try CTA */}
            <div style={{ marginTop: '2.5rem', padding: '1.5rem', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
              <p style={{ color: 'var(--text)', fontWeight: 600, marginBottom: '1rem', fontSize: '0.95rem' }}>
                Also try our other free tools:
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <Link href="/decision-wheel" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)', textDecoration: 'none', fontWeight: 600, fontSize: '0.9rem' }}>
                  🎯 Decision Wheel — Spin to resolve any everyday choice
                </Link>
                <Link href="/spirit-animal" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary)', textDecoration: 'none', fontWeight: 600, fontSize: '0.9rem' }}>
                  🐾 Spirit Animal Wheel — Discover your inner animal
                </Link>
              </div>
            </div>
          </div>

          {/* FAQ */}
          <div>
            <h2 style={h2Style}>Frequently Asked Questions</h2>
            <FAQAccordion />
          </div>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────── */}
      <footer style={{ background: 'var(--surface)', borderTop: '1px solid var(--border)', padding: '3rem 1.5rem', marginTop: '2rem' }}>
        <div style={{ maxWidth: '1024px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '2rem' }}>
          <div>
            <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: '1.25rem', color: 'var(--text)', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ color: 'var(--primary)' }}>●</span> UniqueBusinessName
            </div>
            <p style={{ color: 'var(--text-dim)', fontSize: '0.9rem', lineHeight: 1.5, maxWidth: '280px' }}>
              The most advanced, physics-driven business name generator on the web. Spin, decide, and conquer.
            </p>
          </div>

          <div>
            <h4 style={{ color: 'var(--text)', fontWeight: 600, marginBottom: '1rem', fontSize: '0.95rem' }}>Tools</h4>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <Link href="/" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Business Name Generator</Link>
              <Link href="/decision-wheel" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Decision Wheel</Link>
              <Link href="/spirit-animal" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Spirit Animal Wheel</Link>
              <Link href="/logo-maker" style={{ color: 'var(--primary)', textDecoration: 'none', fontSize: '0.9rem', fontWeight: 600 }}>✦ Logo Maker</Link>
            </div>
          </div>

          <div>
            <h4 style={{ color: 'var(--text)', fontWeight: 600, marginBottom: '1rem', fontSize: '0.95rem' }}>Company</h4>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <Link href="/about" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>About Us</Link>
              <Link href="/contact" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Contact</Link>
              <Link href="/blog" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Blog</Link>
              <Link href="/privacy" style={{ color: 'var(--text-muted)', textDecoration: 'none', fontSize: '0.9rem' }}>Privacy Policy</Link>
            </div>
          </div>
        </div>
        <div style={{ maxWidth: '1024px', margin: '3rem auto 0', paddingTop: '2rem', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
          <p style={{ color: 'var(--text-dim)', fontSize: '0.85rem', margin: 0 }}>
            © {new Date().getFullYear()} UniqueBusinessName.com. All rights reserved.
          </p>
          <button
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            style={{ background: 'var(--surface-2)', border: '1px solid var(--border)', color: 'var(--text-muted)', padding: '0.5rem 1rem', borderRadius: '999px', fontSize: '0.85rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.5rem' }}
          >
            Back to top ↑
          </button>
        </div>
      </footer>
    </div>
  );
}
